import{a as w,S as v,i as a}from"./assets/vendor-5YrzWRhu.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))s(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function t(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(o){if(o.ep)return;o.ep=!0;const r=t(o);fetch(o.href,r)}})();const S="51880521-c3154ecfaa100b1983789291c",q="https://pixabay.com/api/";async function p(i,e){const t={key:S,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15};return(await w.get(q,{params:t})).data}const f=document.querySelector(".gallery"),h=document.querySelector(".loader"),g=document.querySelector(".load-button"),E=new v(".gallery a",{captionsData:"alt",captionDelay:250});function y(i){const e=i.map(t=>`
        <li class="gallery-item">
          <a href="${t.largeImageURL}">
            <img src="${t.webformatURL}" alt="${t.tags}" loading="lazy"/>
          </a>
          <div class="info">
            <p><b>Likes:</b> ${t.likes}</p>
            <p><b>Views:</b> ${t.views}</p>
            <p><b>Comments:</b> ${t.comments}</p>
            <p><b>Downloads:</b> ${t.downloads}</p>
          </div>
        </li>
      `).join("");f.insertAdjacentHTML("beforeend",e),E.refresh()}function R(){f.innerHTML=""}function P(){h.classList.add("hidden")}function B(){h.classList.remove("hidden")}function m(){g.classList.add("hidden")}function b(){g.classList.remove("hidden")}const L=document.querySelector(".form"),$=L.querySelector('input[name="search-text"]'),M=document.querySelector(".load-button");let l="",n=1,c=15,u=0;m();L.addEventListener("submit",async i=>{if(i.preventDefault(),l=$.value.trim(),n=1,l===""){a.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}R(),m(),B();try{const e=await p(l,n,c);if(u=e.totalHits,!e.hits.length){a.error({title:"Sorry",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(e.hits);const t=document.querySelector(".gallery li");if(t){const s=t.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}n<Math.ceil(u/c)?b():a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(e){a.error({title:"Error",message:"Something went wrong! Please try again later.",position:"topRight"}),console.error(e)}finally{P()}});M.addEventListener("click",async i=>{i.preventDefault(),n+=1;try{const e=await p(l,n,c);y(e.hits);const t=document.querySelector(".gallery li");if(t){const s=t.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}n>=Math.ceil(u/c)&&(b(),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(e){a.error({title:"Error",message:"Failed to load more images!",position:"topRight"}),console.error(e)}});
//# sourceMappingURL=index.js.map
